[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[project]
name = "data_indexer"
version = "0.0.9"
dependencies = [
    "beautifulsoup4 == 4.11.1",
    "spacepy==0.4.1",
    "httpx==0.23.0"
]