[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[project]
name = "data_indexer"
version = "0.0.4"
dependencies = [
    "beautifulsoup4 == 4.11.1",
    "spacepy==0.4.1",
    "certifi==2021.10.8"
]