name: Manually Run Indexer

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment to create index file for
        options:
          - Development
          - Production

permissions:
  contents: write

jobs:
  run_indexer:
    uses: ./.github/workflows/base-run-indexer.yml
    with:
      environment: ${{inputs.environment}}