name: Manually Run Indexer

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run_indexer:
    uses: ./.github/workflows/base-run-indexer.yml
    with:
      imap_api_download_url: ${{vars.IMAP_API_DOWNLOAD_URL}}
      data_access_url: ${{vars.DATA_ACCESS_URL}}
      index_file_descriptor: ${{vars.INDEX_FILE_DESCRIPTOR}}
      environment: Development
    secrets:
      imap_api_key: ${{secrets.IMAP_API_KEY}}