name: Manually Run Indexer

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment to create index file for
        options:
          - Development
          - Production
      indexer_type:
        type: choice
        description: Mission indexer to create
        options:
          - imap
          - psp

permissions:
  contents: write

jobs:
  run_indexer:
    runs-on: ubuntu-latest

    environment: ${{inputs.environment}}
    env:
      IMAP_API_DOWNLOAD_URL: ${{vars.IMAP_API_DOWNLOAD_URL}}
      IMAP_DATA_ACCESS_URL: ${{vars.DATA_ACCESS_URL}}
      IMAP_API_KEY: ${{secrets.IMAP_API_KEY}}
      INDEX_FILE_DESCRIPTOR: ${{vars.INDEX_FILE_DESCRIPTOR}}

    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: Set up uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: "3.13"
    - name: Run Index
      run: |
        uv run main.py ${{inputs.indexer_type}}
    - name: Commit and Push
      run: |
        git pull
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git diff --cached --quiet || git commit -m "Automatically update ${{inputs.indexer_type}} index file"
        git push


