name: Run Indexer

on:
  push:
    branches: [ "main" ]
  schedule:
  - cron: '55 * * * *'

permissions:
  contents: write

jobs:
  run_indexer:
    strategy:
      matrix:
        indexer_type: [imap, psp]
      fail-fast: false
      max-parallel: 1

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Index
      run: |
        python main.py ${{matrix.indexer_type}}
    - name: Commit and Push
      run: |
        git pull
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git diff --cached --quiet || git commit -m "Automatically update ${{matrix.indexer_type}} index file"
        git push
