name: Run Indexer

on:
  push:
    branches: [ "main" ]
  schedule:
  - cron: '55 * * * *'

permissions:
  contents: write

jobs:
  run_indexer:
    uses: ./.github/workflows/base-run-indexer.yml
    with:
      environment: Development
