name: Run Indexer

on:
  push:
    branches: [ "main" ]
  schedule:
  - cron: '55 * * * *'

permissions:
  contents: write

jobs:
  run_indexer:
    strategy:
      matrix:
        environment: [Development]
      max-parallel: 1
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/workflows/base-run-indexer.yml
      with:
        environment: ${{matrix.environment}}
